spring:
  datasource:
    url: jdbc:mariadb://localhost:13306
    driver-class-name: org.mariadb.jdbc.Driver
    username: numo
    password: numo12110!

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.domain,com.example.demo.vo

logging:
  level:
    com.example.demo.mapper: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG