spring:
  datasource:
    url: jdbc:mariadb://localhost:13306
    driver-class-name: org.mariadb.jdbc.Driver
    username: numo
    password: numo12110!

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.domain
